## Feature Scaling
+ In ML models, features are mapped into n-dimensional space
+ so, if there are 2 variables (x,y) that are mapped in a 2D co-ordinate system
+ if 1 variable, ex y, is very huge, while x is very small,then the bigger one will dominate the smaller one
+ as a result, the model will see a loss in valuable information
+ so will need feature scaling to solve this problem

### there are 3 most-used ways to scale features:


1. **Min Max Scaling:** This will scale the input to have minimu of 0 and maximum of 1. That is, it scales the data in the range of [0,1]. This is useful when the parameters have to be on the same positive scale. But, the outliers are lost
***
2. **Standardization:** This will scale the input to have a mean of 0, and a variance of 1
***
3. **Normalizing:** This will scale the input to make the norm of 1. For instance, for 3D data the 3 independent variables will lie on a unit sphere.
***
4. **Log Transformation:** Taking the log of data after any of the above transformations

**For msot applications, Standardization is recommended**
+ Min Max Scaling is recommended for neural networks
+ Normalizing is recommended when clustering (k-means)

In [6]:
import pandas as opd
import numpy as np
from sklearn.preprocessing import StandardScaler, Normalizer, MinMaxScaler

df = pd.read_csv('euro_data.csv').dropna()
df
X = df[['Age', 'Salary']].values.astype(np.float64)

In [7]:
standard_scaler = StandardScaler()
normalizer = Normalizer()
min_max_scaler = MinMaxScaler()

print('Standardization: ')
print(standard_scaler.fit_transform(X))
print(" ")
print("Normalization: ")
print(normalizer.fit_transform(X))
print(" ")
print("MinMax scaling: ")
print(min_max_scaler.fit_transform(X))

Standardization: 
[[ 0.69985807  0.58989097]
 [-1.51364653 -1.50749915]
 [-1.12302807 -0.98315162]
 [-0.08137885 -0.37141284]
 [-0.47199731 -0.6335866 ]
 [ 1.22068269  1.20162976]
 [ 1.48109499  1.55119478]
 [-0.211585    0.1529347 ]]
 
Normalization: 
[[6.11110997e-04 9.99999813e-01]
 [5.62499911e-04 9.99999842e-01]
 [5.55555470e-04 9.99999846e-01]
 [6.22950699e-04 9.99999806e-01]
 [6.03448166e-04 9.99999818e-01]
 [6.07594825e-04 9.99999815e-01]
 [6.02409529e-04 9.99999819e-01]
 [5.52238722e-04 9.99999848e-01]]
 
MinMax scaling: 
[[0.73913043 0.68571429]
 [0.         0.        ]
 [0.13043478 0.17142857]
 [0.47826087 0.37142857]
 [0.34782609 0.28571429]
 [0.91304348 0.88571429]
 [1.         1.        ]
 [0.43478261 0.54285714]]
