Numpy enables fast computation in Python -- the underlying implementation is in C so it's very fast.
The key feature of NumPy is the 'ndarray' object.
The data type should be homogenous; the array should contain elements of single data type

In [ ]:
import numpy as np

In [3]:
vector = np.array([1,2,3,4])
print("Vector {}".format(vector))
# every array will have a shape - as demarkated by its dimensions
print("Shape {}".format(vector.shape))

# print # of dimensions
print("Dim: {}".format(vector.ndim))
print("Data type: {}".format(vector.dtype))


Vector [1 2 3 4]
Shape (4,)
Dim: 1
Data type: int64


The number of dimensions numpy uses is as follows:
`(depth, rows, columns)`
So a 3D array of 3 rows, 2 columns and 2 depth will ahve the following shape:
(2, 3, 2)

In [4]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
v.shape = (2, 3, 2)
print(v)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [6]:
v = np.zeros((2,3,2))
print(v)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


## arange
+ The `arange` function is similar to Python's 'range' function
+ the data type, is not specified, will be np.float(64)

In [7]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## zeros, zeros_like
+ `zeros(dim)` will return a np.array of 'dim' dimensions initialzied with 0. Note that dim should be a tuple
+ `zeros_like(array)` will return a np.array of same dimensions as of array, initialized with zeros
+ the same functionality applies for 'ones' and 'ones_like'
+ as well as for 'empty' and 'empty_like'

In [9]:
print("zeros")
a = np.zeros((3,3))
print("a: {}".format(a))

b = np.zeros_like(a)
print('B: {}'.format(b))
print('-'*75)
print('\nOnes')
a = np.ones((3,3))
print('a: {}'.format(a))
b = np.ones_like(a)
print('b: {}'.format(b))
print('-'*75)
print('\nEmpty')
a = np.empty((3,3))
print('a: {}'.format(a))
b = np.empty_like(a)
print('b: {}'.format(b))

zeros
a: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
B: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------------------------------------------------------------------------

Ones
a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
b: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
---------------------------------------------------------------------------

Empty
a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
b: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## astype
+ `astype` will convert 1 data type to another
+ `astype` will create a new copy of the input array - even if the data type is the same



In [12]:
a = np.array([1, 2, 3, 4.5, 6.7])
print('a: {}, dtype: {}'.format(a, a.dtype))
b = a.astype(int)
print('b: {}, dtype: {}'.format(b, b.dtype))

a: [1.  2.  3.  4.5 6.7], dtype: float64
b: [1 2 3 4 6], dtype: int64


## Vectorization and vector-scalar operations
+ Using `for loops` in code is not only prone to error, but also is inefficent
+ can use NumPy to cirucmvent for loops through `vectorization`

In [13]:
a = np.array([[1, 2,3], [4, 5, 6]])
b = np.array([[4, 5, 6], [1, 2, 3]])

c = a + b
print(c)

c = a * b
print(c)

c = a - b
print(c)

[[5 7 9]
 [5 7 9]]
[[ 4 10 18]
 [ 4 10 18]]
[[-3 -3 -3]
 [ 3  3  3]]


+ Using scalars with vector will produce element-wise operations

In [14]:
a = 3
b = np.array([[1, 2, 3], [4, 5, 6]])

c = a + b
print(c)
print('-'*10)
c = a*b
print(c)
print('-'*10)
c = 1.0/b
print(c)

[[4 5 6]
 [7 8 9]]
----------
[[ 3  6  9]
 [12 15 18]]
----------
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


## Slicing

+ You can slice by the following syntax:
+ `array[start_index: end_index]`

+ for n-dimensional array:
+ `array[start_index:end_index, start_index: end_index]`



In [15]:
a = np.arange(20)
print(a)
print('-'*20)
a[10:15] = 5
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
--------------------
[ 0  1  2  3  4  5  6  7  8  9  5  5  5  5  5 15 16 17 18 19]


+ to avoid the above senario, can use `copy()`

In [16]:
a = np.arange(20)
print(a)
print('-'*30)
print(" ")
b = a[10:15].copy()
b = 5
print(a) # value in the original array does not change

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
------------------------------
 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


+ Slicing by `:` will take the entire axis. So:
1. `arr2d[:,0]` --> will reutn array of shape (3,)
2. `arr2d[:, :1]` --> will return array of shape (3,1)

## Boolean indexing
+ Using boolean indeing, can use it to filter or check if any entries have any specific values

In [17]:
a = np.array(['Brendan', 'is', 'an', 'awesome', 'coder'])
a == 'Brendan' # returns Boolean array

array([ True, False, False, False, False])

In [18]:
# lists entry where valie != 'Brendan'
a[~(a == "Brendan")]

array(['is', 'an', 'awesome', 'coder'], dtype='<U7')

+ Can use `|` for `or` and `&` for `and`; but Python's `and`, `or` will not work with Numpy indexing

In [19]:
(a == "Brendan") | (a=='coder')

array([ True, False, False, False,  True])

## Fancy indexing
+ you can index a list to print the array in the given order.
+ for example, to print the first row, 3rd row and 2nd row, in that order

In [20]:
a = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
print(a)
a[[1, 3, 2]]

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


array([[2, 2, 2],
       [4, 4, 4],
       [3, 3, 3]])

## Transposing
+ can obtain the transpose of the matrix using `matrix.T` where `matrix` is the matrix name

In [21]:
a = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
print(a.T)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


# Univerrsal Functions
+ NumPy has a variety of functions that can be applied to scalars, as we ll as vectors
+ examples: sqrt, exp, log, log10, sin, cos, arcsin

In [22]:
a = 20
b = np.random.rand(2,2)
print(np.exp(a))
print(np.exp(b))

485165195.4097903
[[1.13399082 1.55663219]
 [1.48626796 2.46391036]]


## meshgrid
+ This is one of the most useful functions
+ It is used to visualize data boundaries of the classifiers
+ to start, train the classifier, then create a `meshgrid` of every pixel in the plot, then classify the pixel
+ when you give the pixel a specific color according to the labeled class, can visualzie the boundaries

+ As follows:
1) Create xs (1D array)
2) create ys (1D array)
3) create meshgrid (2D array) which correspodns to every pixel in the graph.


In [24]:
xs = np.linspace(1, 10, 100)
ys = np.linspace(1, 10, 100)
xx, yy = np.meshgrid(xs, ys)

## Where
+ if have 3 arrays x, y and condition then, `np.where` is a replcaement for using an if/else

In [25]:
a = [0, -1, 2, 3, -4, -5]
b = [9, 3, 4, 11, 2, 3]
c = [True, False, True, True, False, True]
np.where(c, a, b)

array([ 0,  3,  2,  3,  2, -5])

## mean, sum, std

In [26]:
a = np.random.rand(3,3)
print(a)
print(np.mean(a))
print(a.mean())

print(np.std(a))

[[0.05375034 0.94807048 0.22542186]
 [0.36655549 0.14258136 0.60104201]
 [0.30948953 0.97512278 0.05538798]]
0.40860242580816997
0.40860242580816997
0.33592296995843157
